package com.suraj.sport.paymentservice.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Represents a payment record for a sports event booking.
 *
 * This entity is the core of the Payment Service — it tracks the payment
 * lifecycle for a booking from initiation to completion or refund.
 *
 * Relationships:
 *   - One Payment → Many Transactions (each payment attempt is a separate transaction)
 *   - One Payment → Many Refunds (supports partial and full refunds)
 *
 * Note: Amount, seatsBooked, pricePerSeat are intentionally NOT duplicated here
 * as they already exist in Booking Service. Payment Service only owns payment
 * and financial transaction concerns.
 *
 * Note: bookingId, eventId, userId are plain Long references — no FK constraints
 * across microservices. Each service owns its own data.
 */
@Entity
@Table(name = "payments")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Reference to Booking Service — no FK constraint, microservices own their data
    @Column(nullable = false)
    private Long bookingId;

    // Reference to Event Service — stored for auditing and reporting purposes
    @Column(nullable = false)
    private Long eventId;

    // Reference to User Service — who made the payment
    @Column(nullable = false)
    private Long userId;

    // Total amount to be paid — passed from Booking Service at initiation
    @Column(nullable = false)
    private double amount;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentStatus paymentStatus;

    // Payment method used — e.g. CREDIT_CARD, DEBIT_CARD, UPI, NET_BANKING
    // TODO: Convert to enum once all supported payment methods are finalized
    private String paymentMethod;

    // Receipt URL generated by payment gateway after successful payment
    // Null until payment succeeds
    private String receiptUrl;

    // All transaction attempts for this payment — one payment can have multiple attempts
    @OneToMany(mappedBy = "payment", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Transaction> transactions;

    // All refunds for this payment — supports partial and full refunds
    @OneToMany(mappedBy = "payment", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Refund> refunds;

    @Builder.Default
    @Column(name = "is_deleted", nullable = false)
    private boolean isDeleted = false;

    private LocalDateTime deletedAt;

    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;
}