spring:
  application:
    name: booking-service   # must match config file names in config server
  profiles:
    active: default     # default profile to activate
  config:
    import: optional:configserver:http://localhost:8071